-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 21:13:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_CLIENTES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_CLIENTES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_CLIENTES` DEFAULT CHARACTER SET utf8 ;
USE `DB_CLIENTES` ;

-- -----------------------------------------------------
-- Table `DB_CLIENTES`.`TB_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CLIENTES`.`TB_CLIENTE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `dtnasc` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `estadocivil` VARCHAR(30) NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
